Include missing constants
As tinyalsa version was changed
(https://github.com/tinyalsa/tinyalsa/tree/v1.0.2)

Some constants were missing (ex:):
system/media/alsa_utils/alsa_device_proxy.c:53:27: error: use of undeclared identifier 'PCM_FORMAT_INVALID'

Change-Id: I0c67e2595017133fa3e4e78bae92a26289416da0